"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gamepad_t(object):
    __slots__ = ["utime", "present", "naxes", "axes", "buttons"]

    def __init__(self):
        self.utime = 0
        self.present = False
        self.naxes = 0
        self.axes = []
        self.buttons = 0

    def encode(self):
        buf = BytesIO()
        buf.write(gamepad_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbi", self.utime, self.present, self.naxes))
        buf.write(struct.pack('>%dd' % self.naxes, *self.axes[:self.naxes]))
        buf.write(struct.pack(">q", self.buttons))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gamepad_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gamepad_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gamepad_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.present = bool(struct.unpack('b', buf.read(1))[0])
        self.naxes = struct.unpack(">i", buf.read(4))[0]
        self.axes = struct.unpack('>%dd' % self.naxes, buf.read(self.naxes * 8))
        self.buttons = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gamepad_t in parents: return 0
        tmphash = (0x345b96879832ec32) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gamepad_t._packed_fingerprint is None:
            gamepad_t._packed_fingerprint = struct.pack(">Q", gamepad_t._get_hash_recursive([]))
        return gamepad_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

